server:
  port: 8002
kafka:
  bootstrap:
    server: localhost:9092
  message:
    topic:
      name: message
  partitioned:
    topic:
      name: partitioned
  filtered:
    topic:
      name: filtered
  orders:
    topic:
      name: orders
    